version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - tasktopia
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - tasktopia
  server:
    container_name: server
    depends_on:
      - mongo
      - redis
    build: ./server
    environment:
      - DB_HOST=mongo
      - REDIS_HOST=redis
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app-server
      - /app-server/node_modules
    command: npm start
    networks:
      - tasktopia
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app-client
      - /app-client/node_modules
    command: npm run start
    networks:
      - tasktopia
networks:
  tasktopia:
    driver: bridge
volumes:
  mongo:
  redis: