version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - tasktopia
  server:
    container_name: server
    depends_on:
      - serviceName: mongo
        condition: service_healthy
    build: ./server
    environment:
      - DB_HOST=mongo
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app-server
    command: npm start
    networks:
      - tasktopia
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app-client
    command: npm start
    networks:
      - tasktopia
networks:
  tasktopia:
    driver: bridge
